### ISSUE TITLE
Chromium VS WebKit

### ISSUE THREAD

**Issue by arsoba** [Screenly/ScreenlyOSE-WebView#19]
Hi! Just curiosity. Why don't you use qtwebengine?

**Comment by vpetersson** [comment]
@arsoba Largely because of legacy reasons. Qtwebengine wasn't around (to my knowledge) when we started working on this. It probably does make sense to switch to it at some point.

**Comment by arsoba** [comment]
@vpetersson I see. I'm not good with Qt, but, as I see, Qtwebengine's classes have the same interface as qtwebview.

**Comment by vpetersson** [comment]
Yes, my understanding is that moving between the two is fairly straight forward.
